# -*- coding: utf-8 -*-
"""Aula 2 Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apbgVmM1D-9A9RM2o8-0WPLlSRxhNMWw
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/movies.csv" 
filmes = pd.read_csv(url) #dataframe
filmes.head()

filmes.columns = (["filmeId", "titulos", "generos"])
filmes.head()

url = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula1.2/ratings.csv"
notas = pd.read_csv(url)
notas.head()

notas.columns = ["usuarioId", "filmeId", "nota", "tempo"]
notas.head()

notas ["nota"].head() #series

notas ["nota"].unique()

notas ["nota"].mean()

notas ["nota"].min()

notas ["nota"].max()

notas.describe()

#explicação sobre a importância da média e da mediana para descrição de dados

