# -*- coding: utf-8 -*-
"""Aula 1 Python - Colab Researsh

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1br5tTYddQhNSxm2yknkw3CdGbw-14sPy
"""

nome = "Sidelia"
print(nome)

idade = 31
idade

idade+3

idade

idade = idade + 3
idade

idade

def mais_um_ano(idade):
    print("ta dentro dessa função")
    return idade +1

mais_um_ano(43)

filme1="Toy Story 17"
filme2="A Xuxa contra o Baixo Astral"
filme3= "Matrix 1"

filmes = ["Toy Story 17", "Xuxa contra o Baixo Astral", "Matrix 1"]

filmes = [filme1, filme2, filme3]

list[]

def imprime_filmes(filmes_que_quero_imprimir):
  print("A lista de filmes que eu tenho disponível")
  print(filmes_que_quero_imprimir)

imprime_filmes(filmes)
imprime_filmes(filmes)
imprime_filmes(filmes)

filmes[1]

filmes[2]

filmes[-1]

filmes[-2]

filmes[1:]

filmes[0:]

for filme in filmes:
  print(filmes)
  print("...")
print("estou fora")

def imprime_filmes(filmes_que_quero_imprimir):
  print("A lista de filmes que eu tenho disponível")
  for filme in filmes:
   print(filmes_que_quero_imprimir)
   print(filmes)

imprime_filmes(filmes)

dados = {"nome" : "Guilherme", 
        "idade" : 37,
        "empresa" : "Alura"}
dados

dados ["nome"]

