# -*- coding: utf-8 -*-
"""Aula4 - Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14kGivzs0EEQJrKPB8p5AOaDKdzzXmexJ
"""

#pelo longo?
#pernacurta?
#faz auau?

porco1 = [0,1,0]
porco2 = [0,1,1]
porco3 = [1,1,1]

cachorro1 = [0,1,1]
cachorro2 = [1,0,1]
cachorro3 = [1,1,1]

treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1,1,1,0,0,0] # 0 cachorro, 1 porco

from sklearn.svm import LinearSVC
modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

animal_misterioso = [1,1,1]
modelo.predict([animal_misterioso])

misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0,1,1]

"""é importante treinar o algoritmo com vários exemplos, para que o algoritmo aprenda e não decore."""

previsoes = modelo.predict(teste_x)
previsoes

"""não existe acurácia alta de inicio, algo está errado no programa"""

from sklearn.metrics import accuracy_score

accuracy_score(teste_y, previsoes)

import pandas as pd

url = "https://raw.githubusercontent.com/guilhermesilveira/machine-learning/master/capitulo2/acesso.csv"
dados = pd.read_csv(url)
dados.head()

dados.sample(5)

x = dados[["home", "como_funciona", "contato"]]
x.head()

